### ISSUE TITLE
Error: Request has been terminated for native http server

### ISSUE THREAD

**Issue by talentlessguy** [asos-craigmorten/superdeno#35]
# Issue

Setup:

- Deno Version: 1.15.2
- v8 Version: 9.5.172.19
- Typescript Version: 4.4.2
- SuperDeno Version: 4.6.0

## Details

```ts
import { superdeno } from 'https://deno.land/x/superdeno@4.6.0/mod.ts'
import { it, run } from 'https://deno.land/x/tincan@1.0.0/mod.ts'
import { App } from 'https://denopkg.com/deno-libs/tinyhttp@new-std-http/mod.ts'

it('simple test', async () => {
  const app = new App()

  const request = superdeno(app._server!) // or `app.handler`, it doesn't work either way

  await request.get('/').expect(404, 'Not Found')
})

run()
```

Error message:

```
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at Test.Request.crossDomainError (https://jspm.dev/npm:superagent@6.1.0!cjs:674:13)
    at XMLHttpRequestSham.xhr.onreadystatechange (https://jspm.dev/npm:superagent@6.1.0!cjs:777:19)
    at XMLHttpRequestSham.xhrReceive (https://deno.land/x/superdeno@4.6.0/src/xhrSham.js:115:29)
    at https://deno.land/x/superdeno@4.6.0/src/xhrSham.js:62:21
    at Object.xhr.onreadystatechange (https://deno.land/x/superdeno@4.6.0/src/xhrSham.js:211:7)
    at XMLHttpRequestSham.xhrSend (https://deno.land/x/superdeno@4.6.0/src/xhrSham.js:335:20)
    at async XMLHttpRequestSham.send (https://deno.land/x/superdeno@4.6.0/src/xhrSham.js:61:7)
```

**Comment by cmorten** [comment]
So the error seeing internally with some extra logging is:

```console
TypeError: error sending request for url (http://127.0.0.1:54365/): connection closed before message completed
    at async mainFetch (deno:ext/fetch/26_fetch.js:265:14)
```

Yet to determine if an issue with superdeno, tinyhttp, or the compat between the two.

**Comment by cmorten** [comment]
Digging further, this is the output from logging the request passed into `app.handle` from tinyhttp, and the subsequent error that it throws:

```console
request Request {
  bodyUsed: false,
  headers: Headers {
  accept: "*/*",
  "accept-encoding": "gzip, br",
  host: "127.0.0.1:54765",
  "user-agent": "Deno/1.16.2"
},
  method: "GET",
  redirect: "follow",
  url: "http://127.0.0.1:54765/"
}

app error TypeError: Cannot read properties of undefined (reading 'settings')
    at handler (https://denopkg.com/deno-libs/tinyhttp@new-std-http/app.ts:216:33)
    at Server.handler (file:///Users/craigmorten/git/asos-craigmorten/superdeno/src/superdeno.ts:90:34)
    at Server.#respond (https://deno.land/std@0.115.1/http/server.ts:350:43)
    at Server.#serveHttp (https://deno.land/std@0.115.1/http/server.ts:396:20)
```

It appears that the issue lies with the handler having some implicit reliance on a bootstrapping step where `this.settings` is populated, but in the case of using `app.handler` standalone this isn't happening --> https://github.com/deno-libs/tinyhttp/blob/new-std-http/app.ts#L216

**Comment by cmorten** [comment]
Going to add some error logging to `superdeno` so it is clearer when it is the underlying app handler at fault and what the error is.

**Comment by cmorten** [comment]
Have released https://deno.land/x/superdeno@4.7.1 which should be more useful when debugging issues in future. Issue appears to lie with `tinyhttp` so closing the issue. Feel free to reopen if find otherwise!

**Comment by talentlessguy** [comment]
@cmorten sorry for taking too much of your time, but even with `app.attach` (which calls `setImmediate`) and with binding to `app` context this still happens:

```ts
import { superdeno } from 'https://deno.land/x/superdeno@4.7.2/mod.ts'
import { describe, it, expect, run } from 'https://deno.land/x/tincan@1.0.0/mod.ts'
import { App } from './app.ts'

it('Custom noMatchHandler works', async () => {
  const app = new App({
    noMatchHandler: (req, res) => {
      res.status = 404
      res.body = `Oopsie! Page ${req.url} is lost.`
    }
  })

  const request = superdeno(app.attach.bind(app))

  await request.get('/').expect(404, 'Oopsie! Page / is lost.')
})

run()
```

```
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at Test.Request.crossDomainError (https://jspm.dev/npm:superagent@6.1.0!cjs:674:13)
    at XMLHttpRequestSham.xhr.onreadystatechange (https://jspm.dev/npm:superagent@6.1.0!cjs:777:19)
    at XMLHttpRequestSham.xhrReceive (https://deno.land/x/superdeno@4.7.2/src/xhrSham.js:115:29)
    at https://deno.land/x/superdeno@4.7.2/src/xhrSham.js:62:21
    at Object.xhr.onreadystatechange (https://deno.land/x/superdeno@4.7.2/src/xhrSham.js:211:7)
    at XMLHttpRequestSham.xhrSend (https://deno.land/x/superdeno@4.7.2/src/xhrSham.js:336:20)
    at async XMLHttpRequestSham.send (https://deno.land/x/superdeno@4.7.2/src/xhrSham.js:61:7)
```
